### ISSUE TITLE
Firefox inserts <br class=""> linebreaks on pressing return

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-gt-tools#45]
I reopened the page `417576986_0013.jpg` and now the encoding of the text looks like this:

![repopen-encoding](https://cloud.githubusercontent.com/assets/5199995/14891303/7345ad7a-0d66-11e6-817f-e2b3a6015b34.png)

**Comment by kba** [comment]
That first one is a right out bug (also happens in the "Spickzettel"). I created #46 for that one.

The second one happens when Firefox inserts a newline. It shouldn't do that. In fact I would completely forbid newlines in the transcription. Or is there a need to transcribe (wrongly detected) images containing multiple lines? @stweil @zuphilip

**Comment by zuphilip** [comment]
Fine for me to forbid completely newlines in the transcription.

**Comment by LetschM** [comment]
I also think newlines are not needed or useful in the transcription. We only need a kind of separator in the comment line (like semicolon or break) to keep different comments apart.
